### ISSUE TITLE
"The developer of this mod has denied third party applications from downloading it"

### ISSUE THREAD

**Issue by ghost** [LemonCaramel/Chameleon#4]
Hi, I'm getting this error when trying to download your mod on CurseForge with [Ferium](https://github.com/gorilla-devs/ferium). I'm assume it was an intentional choice to limit third-party downloads, so I guess this issue is to bring up a discussion on why.

**Comment by LemonCaramel** [comment]
I didn't mean it. I don't live in an English-speaking country, so I made some setting mistake.
It will probably work well now. If the problem persists, please re-open the issue.
